spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/parent?serverTimezone=UTC
    username: root
    password: 1234
    driverClassName: com.mysql.cj.jdbc.Driver
#控制台输出Sql
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
